Description: A VPC for a company that contains 2 subnets, 1 public, 1 private, and multiple EC2 instances

# Resources section
Resources:
  FridayHITTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      InstanceTenancy: default
      EnableDnsHostnames: false
      Tags:
        - Value: FridayHITTVPC
          Key: Name
  FridayHITTRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FridayHITTVPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Value: InternetGateway
          Key: Name
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FridayHITTVPC
      InternetGatewayId: !Ref InternetGateway
  FridayHITTPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FridayHITTVPC
      AvailabilityZoneId: use1-az4
      CidrBlock: 10.0.0.0/22
      Tags:
        - Value: public
          Key: public/private
        - Value: FridayHITTPublicSubnet
          Key: Name
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref FridayHITTRouteTable
      SubnetId: !Ref FridayHITTPublicSubnet
  FridayHITTPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FridayHITTVPC
      AvailabilityZoneId: use1-az4
      CidrBlock: 10.0.4.0/23
      Tags:
        - Value: FridayHITTPrivateSubnet
          Key: Name
        - Value: private
          Key: public/private
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref FridayHITTRouteTable
      SubnetId: !Ref FridayHITTPrivateSubnet